administration/urls.py
# from administration.models import Branch
from django.urls import path
from administration import views
app_name = 'administration'
urlpatterns = [
    path('',                        views.HomePageView.as_view(),   name='home'),
    path('sign-up/',                views.add_user,                 name='add_user'),
    path('my-profile/',             views.my_profile,               name='my_profile'),
    path('edit-profile/<str:pk>',   views.edit_user,                name='edit_user'),
    path('add-address/<str:pk>',    views.add_address,              name='add_address'),
    path('edit-address/<str:pk>',   views.edit_address,             name='edit_address'),


    
]

order/urls.py
# from administration.models import Branch
from django.urls import path
from order import api
from order import views

app_name = 'order'
urlpatterns = [
    path('api/add-to-cart/<str:product_id>/',           api.AddToCart.as_view()),       #   add product to 
    path('your-cart/',              views.cart_list,    name='cart_list'),
    path('confirmation/<str:pk>',   views.confirmation,    name='confirmation'),

    
]

product_management/urls.py
# from administration.models import Branch
from django.urls import path
from product_management import views
app_name = 'product_management'

urlpatterns = [
    path('product-detail/<str:pk>', views.product_detail, name='product_detail'),
    path('all-products/',           views.ProductList.as_view(), name='product_list'),
    path('search/',                 views.filter_product, name='filter_product'),


]

swan_ecommerce/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',   include('django.contrib.auth.urls')),
    path('',            include('administration.urls', namespace='administration')),
    path('',            include('product_management.urls', namespace='product_management')),
    path('',            include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
  <head>
    <!-- Mobile Specific Meta -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}" />
    <!-- Author Meta -->
    <meta name="author" content="CodePixar" />
    <!-- Meta Description -->
    <meta name="description" content="" />
    <!-- Meta Keyword -->
    <meta name="keywords" content="" />
    <!-- meta character set -->
    <meta charset="UTF-8" />
    <!-- Site Title -->
    <title>{% block title %}{% endblock %}</title>
    {% include 'base/css.html' %} {% block css %} {% endblock %}
  </head>

  <body>
    <!-- Start Header Area -->
    <header class="header_area sticky-header">
      <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand logo_h" href="/"
              ><img src="{% static 'img/logo.png' %}" alt=""
            /></a>
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div
              class="collapse navbar-collapse offset"
              id="navbarSupportedContent"
            >
              {% include 'base/header_menu.html' %}
            </div>
          </div>
        </nav>
      </div>
      {% include 'base/search.html' %}
    </header>
    <!-- End Header Area -->
    {% block containt %} {% endblock %}
    <!-- start footer Area -->
    <footer class="footer-area section_gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Us </h6>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                eiusmod tempor incididunt ut labore dolore magna aliqua.
              </p>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Newsletter</h6>
              <p>Stay update with our latest</p>
              <div class="" id="mc_embed_signup">
                <form
                  target="_blank"
                  novalidate="true"
                  action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                  method="get"
                  class="form-inline"
                >
                  <div class="d-flex flex-row">
                    <input
                      class="form-control"
                      name="EMAIL"
                      placeholder="Enter Email"
                      onfocus="this.placeholder = ''"
                      onblur="this.placeholder = 'Enter Email '"
                      required=""
                      type="email"
                    />

                    <button class="click-btn btn btn-default">
                      <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    </button>
                    <div style="position: absolute; left: -5000px">
                      <input
                        name="b_36c4fd991d266f23781ded980_aefe40901a"
                        tabindex="-1"
                        value=""
                        type="text"
                      />
                    </div>

                    <!-- <div class="col-lg-4 col-md-4">
												<button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
											</div>  -->
                  </div>
                  <div class="info"></div>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget mail-chimp">
              <h6 class="mb-20">Instragram Feed</h6>
              <ul class="instafeed d-flex flex-wrap">
                <li><img src="{% static 'img/i1.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i2.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i3.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i4.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i5.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i6.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i7.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i8.jpg' %}" alt="" /></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-2 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Follow Us</h6>
              <p>Let us be social</p>
              <div class="footer-social d-flex align-items-center">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div
          class="footer-bottom d-flex justify-content-center align-items-center flex-wrap"
        >
          <p class="footer-text m-0">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="fa fa-heart-o" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->

    {% include 'base/js.html' %}
    {% block js %}
    {% endblock %}

  </body>
</html>

templates/base/css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/linearicons.css' %}" />
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
<link rel="stylesheet" href="{% static 'css/nice-select.css' %}" />
<link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}" />
<link rel="stylesheet" href="{% static 'css/ion.rangeSlider.skinFlat.css' %}" />
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
<link rel="stylesheet" href="{% static 'css/main.css' %}" />
{{ form.media }}
<style>
.disabled_field{
    background-color: #eee;
    pointer-events: none;
  }
</style>

templates/base/header_menu.html
{% load static %}
<ul class="nav navbar-nav menu_nav ml-auto">
    <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
    </li>
    <li class="nav-item submenu dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false">Shop</a>
        <ul class="dropdown-menu">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'product_management:product_list' %}">
                    All Products</a>
            </li>
        </ul>
    </li>

    <li class="nav-item submenu dropdown">
        {% if request.user.is_authenticated %}
        Welcome,
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" 
        role="button" aria-haspopup="true" aria-expanded="false">{{request.user.first_name}}</a>

        {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        {% endif %}
        {% if request.user.is_authenticated %}
        <ul class="dropdown-menu">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'administration:my_profile' %}">
                    My Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                    Log Out</a>
            </li>
        </ul>
        {% endif %}


    </li>
</ul>
{% if request.user.is_authenticated %}
<ul class="nav navbar-nav navbar-right">
    <li class="nav-item">
        <a href="{% url 'order:cart_list' %}" class="cart">
            <span class="ti-bag">
            </span>
        </a>
    </li>
    <li class="nav-item">
        <button class="search">
            <span class="lnr lnr-magnifier" id="search">
            </span>
        </button>
    </li>
</ul>
{% endif %}

templates/base/js.html
{% load static %}

<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
  integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
  crossorigin="anonymous"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/countdown.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!--gmaps Js-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
<script src="{% static 'js/gmaps.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script>
  var csrftoken = '{{csrf_token}}';
</script>
<script src="{% static 'order/js/create-order.js' %}"></script>

templates/base/pagination.html
{% load administration_extras %}

        {% if page_obj.has_previous %}
            <a class="prev-arrow" href="{% my_url page_obj.previous_page_number 'page' request.GET.urlencode %}"
                tabindex="-1"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
        {% endif %}
            <a class="active">{{ page_obj.number }}</a>
        {% if page_obj.has_next %}
            <a href="{% my_url page_obj.next_page_number 'page' request.GET.urlencode %}" class="next-arrow"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
        {% endif %}

templates/base/search.html
{% load static %}
<div class="search_input" id="search_input_box">
  <div class="container">
    <form class="d-flex justify-content-between" method='get'
    action="{% url 'product_management:filter_product' %}">
      <input type="text" name="q" class="form-control" id="search_input" placeholder="Search Here"/>
      <button type="submit" class="btn"></button>
      <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
    </form>
  </div>
</div>