administration/urls.py
# from administration.models import Branch
from django.urls import path
from administration import views
app_name = 'administration'
urlpatterns = [
    path('',                        views.HomePageView.as_view(),   name='home'),
    path('sign-up/',                views.add_user,                 name='add_user'),
    path('my-profile/',             views.my_profile,               name='my_profile'),
    path('edit-profile/<str:pk>',   views.edit_user,                name='edit_user'),
    path('add-address/<str:pk>',    views.add_address,              name='add_address'),
    path('edit-address/<str:pk>',   views.edit_address,             name='edit_address'),


    
]

order/urls.py
# from administration.models import Branch
from django.urls import path
from order import api
from order import views

app_name = 'order'
urlpatterns = [
    path('api/add-to-cart/<str:product_id>/',           api.AddToCart.as_view()),       #   add product to 
    path('your-cart/',              views.cart_list,    name='cart_list'),
    path('confirmation/<str:pk>',   views.confirmation,    name='confirmation'),

    
]

product_management/urls.py
# from administration.models import Branch
from django.urls import path
from product_management import views
app_name = 'product_management'

urlpatterns = [
    path('product-detail/<str:pk>', views.product_detail, name='product_detail'),
    path('all-products/',           views.ProductList.as_view(), name='product_list'),
    path('search/',                 views.filter_product, name='filter_product'),


]

swan_ecommerce/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',   include('django.contrib.auth.urls')),
    path('',            include('administration.urls', namespace='administration')),
    path('',            include('product_management.urls', namespace='product_management')),
    path('',            include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/models.py
import uuid
from xmlrpc.client import Boolean
from django.db import models
from django.contrib.auth.models import AbstractUser
from swan_ecommerce.models import BaseModel
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

class ShippingAddress(BaseModel):
    address_1   = models.CharField('Address Line 1', max_length=50, null=True)
    address_2   = models.CharField('Address Line 2', max_length=50, null=True, blank=True)
    city        = models.CharField('City', max_length=50, null=True)
    state       = models.CharField('State', max_length=50, null=True)
    zipcode     = models.CharField('Zipcode', max_length=50, null=True)
    country     = CountryField('Country', null=True, blank=True)
    is_billing  = models.BooleanField('Do you want to set as default billing address?', default=False)
    is_shipping = models.BooleanField('Do you want to set as default shipping address?', default=False)

    def billing(self):
        if self.is_billing:
            return "default Billing Address"
        else:
            return '-'

    def shipping(self):
        if self.is_shipping:
            return "default Shipping Address"
        else:
            return '-'

class RootUser(AbstractUser):
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email       = models.EmailField('Email', null=True)
    phone_no    = PhoneNumberField('Phone Number', null=True)
    phone_no_2  = PhoneNumberField('Alternet Phone Number', null=True, blank=True)
    address     = models.ManyToManyField(ShippingAddress)

    def save(self, *args, **kwargs):
        if self.email:
            self.username = self.email
        super(RootUser, self).save(*args, **kwargs)

administration/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, ButtonHolder, HTML, Div, Field
from .models import *
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django import forms


class SignUpForm(UserCreationForm):
    class Meta:
        model = RootUser
        fields = ['email', 'phone_no','first_name', 'last_name']

    def clean_email(self):
        data = self.cleaned_data['email']
        if not self.instance.email:
            if RootUser.objects.filter(email=data).count() > 0:
                raise forms.ValidationError("User with this email already exists.")
        return data
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column('first_name', css_class='form-group col-md-6 mb-0'),
                Column('last_name', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('email', css_class='form-group col-md-6 mb-0'),
                Column('phone_no', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('password1', css_class='form-group col-md-6 mb-0'),
                Column('password2', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
        )
        for fieldname in ['password1', 'password2']:
            self.fields[fieldname].help_text = None

class RootUserForm(forms.ModelForm):
    class Meta:
        model = RootUser
        fields = ['email', 'phone_no','phone_no_2','first_name', 'last_name',]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column('first_name', css_class='form-group col-md-6 mb-0'),
                Column('last_name', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('email', css_class='form-group col-md-12 mb-0 disabled_field'),
                css_class='form-row'
            ),
            Row(
                Column('phone_no', css_class='form-group col-md-6 mb-0'),
                Column('phone_no_2', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
        )

class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ['address_1', 'address_2','city','state', 'zipcode','country','is_billing','is_shipping']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column('address_1', css_class='form-group col-md-6 mb-0'),
                Column('address_2', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('city', css_class='form-group col-md-6 mb-0'),
                Column('state', css_class='form-group col-md-6 mb-0'),

                css_class='form-row'
            ),
            Row(
                Column('zipcode', css_class='form-group col-md-6 mb-0'),
                Column('country', css_class='form-group  col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('is_billing', css_class='form-group col-md-12 mb-0'),
                css_class='form-row'
            ),            
            Row(
                Column('is_shipping', css_class='form-group col-md-12 mb-0'),
                css_class='form-row'
            ),
        )

administration/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import TemplateView
from administration.forms import *
from django.contrib.auth.decorators import login_required
from product_management.models import *
from order.models import *

class HomePageView(TemplateView):
    template_name = "administration/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_list'] = Product.objects.all()[:20]
        context['uppcoming_product_list'] = Product.objects.filter(quantity=0)[:20]
        context['latest_product'] = Product.objects.all().last()
        return context

def add_user(request):
    form = SignUpForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('login')
    return render(request,'registration/sign_up.html',{'form':form})

def my_profile(request):
    user = RootUser.objects.get(username=request.user.username)
    return render(request,'administration/my_profile.html',{'object':user})

def edit_user(request,pk):
    user = RootUser.objects.get(pk=pk)
    form = RootUserForm(request.POST or None, instance = user)
    if form.is_valid():
        form.save()
        return redirect('administration:my_profile')
    return render(request,'administration/edit_profile.html',{'form':form})

def add_address(request,pk):
    user = RootUser.objects.get(pk=pk)
    form = ShippingAddressForm(request.POST or None)
    if form.is_valid():
        address_obj = form.save(commit=False)
        address_obj.save()
        user.address.add(address_obj)
        user.save()
        billing_address = request.POST.get('is_billing')
        shipping_address = request.POST.get('is_shipping')
        print(billing_address,shipping_address)
        if billing_address:
            for i in user.address.all().exclude(id=address_obj.id):
                i.is_billing = False
                i.save()
        
        if shipping_address:
            for i in user.address.all().exclude(id=address_obj.id):
                i.is_shipping = False
                i.save()
        return redirect('administration:my_profile')
    return render(request,'administration/add_address.html',{'form':form})

def edit_address(request,pk):
    address = ShippingAddress.objects.get(pk=pk)
    form = ShippingAddressForm(request.POST or None,instance = address)
    user = RootUser.objects.get(pk=request.user.pk)
    if form.is_valid():
        address_obj = form.save(commit=False)
        address_obj.save()
        billing_address = request.POST.get('is_billing')
        shipping_address = request.POST.get('is_shipping')
        print(billing_address,shipping_address)
        if billing_address:
            for i in user.address.all().exclude(id=address_obj.id):
                i.is_billing = False
                i.save()
        
        if shipping_address:
            for i in user.address.all().exclude(id=address_obj.id):
                i.is_shipping = False
                i.save()
        
        return redirect('administration:my_profile')
    return render(request,'administration/add_address.html',{'form':form})

administration/templates/administration/add_address.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Add Address {% endblock %}
{% block containt %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center
            justify-content-end">
            <div class="col-first">
                <h1>Add Address</h1>
                <nav class="d-flex align-items-center">
                    <a href="/">Home<span class=""></span></a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Single Product Area =================-->
<div class="product_image_area">
    <div class="container">
        <div class="row s_product_inner">
            <div class="col-lg-3">
            </div>

            <div class="col-lg-6">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="col-md-12 form-group">
                        {% crispy form %}
                    </div>
                    <div class="col-md-12 form-group">
                        <button type="submit" class="primary-btn"> Submit
                        </button>
                    </div>
                </form>
            </div>
            <div class="col-lg-3">
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $('#id_country').addClass('form-control');
    $('#id_country').select2();

</script>
{% endblock %}

administration/templates/administration/edit_profile.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Edit Profile {% endblock %}
{% block containt %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center
            justify-content-end">
            <div class="col-first">
                <h1>Edit Profile</h1>
                <nav class="d-flex align-items-center">
                    <a href="/">Home<span class=""></span></a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Single Product Area =================-->
<div class="product_image_area">
    <div class="container">
        <div class="row s_product_inner">
            <div class="col-lg-3">
            </div>

            <div class="col-lg-6">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="col-md-12 form-group">
                        {% crispy form %}
                    </div>
                    <div class="col-md-12 form-group">
                        <button type="submit" class="primary-btn"> Submit
                        </button>
                    </div>
                </form>
            </div>
            <div class="col-lg-3">
            </div>
        </div>
    </div>



    {% endblock %}

administration/templates/administration/home.html
{% extends "base/base.html" %}
{% load static %}
{% block title %} Home {% endblock %}
{% block containt %}
		<!-- start banner Area -->
		<section class="banner-area">
			<div class="container">
				<div class="row fullscreen align-items-center justify-content-start">
					<div class="col-lg-12">
						<div class="active-banner-slider owl-carousel">
							<!-- single-slide -->
							<div class="row single-slide align-items-center d-flex">
								<div class="col-lg-5 col-md-6">
									<div class="banner-content">
										<h1>Nike New <br>Collection!</h1>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
											eiusmod tempor incididunt ut labore et
											dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
											exercitation.</p>

									</div>
								</div>
								<div class="col-lg-7">
									<div class="banner-img">
										<img class="img-fluid" src="{% static 'img/banner/banner-img.png' %}" alt="">
									</div>
								</div>
							</div>
							<!-- single-slide -->
							<div class="row single-slide">
								<div class="col-lg-5">
									<div class="banner-content">
										<h1>Nike New <br>Collection!</h1>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
											eiusmod tempor incididunt ut labore et
											dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
											exercitation.</p>

									</div>
								</div>
								<div class="col-lg-7">
									<div class="banner-img">
										<img class="img-fluid" src="{% static 'img/banner/banner-img.png' %}" alt="">
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End banner Area -->
<!-- start features Area -->
<section class="features-area section_gap">
    <div class="container">
        <div class="row features-inner">
            <!-- single features -->
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-features">
                    <div class="f-icon">
                        <img src="{% static 'img/features/f-icon1.png' %}" alt="" />
                    </div>
                    <h6>Free Delivery</h6>
                    <p>Free Shipping on all order</p>
                </div>
            </div>
            <!-- single features -->
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-features">
                    <div class="f-icon">
                        <img src="{% static 'img/features/f-icon2.png' %}" alt="" />
                    </div>
                    <h6>Return Policy</h6>
                    <p>Free Shipping on all order</p>
                </div>
            </div>
            <!-- single features -->
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-features">
                    <div class="f-icon">
                        <img src="{% static 'img/features/f-icon3.png' %}" alt="" />
                    </div>
                    <h6>24/7 Support</h6>
                    <p>Free Shipping on all order</p>
                </div>
            </div>
            <!-- single features -->
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-features">
                    <div class="f-icon">
                        <img src="{% static 'img/features/f-icon4.png' %}" alt="" />
                    </div>
                    <h6>Secure Payment</h6>
                    <p>Free Shipping on all order</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end features Area -->
<!-- Start category Area -->
<section class="category-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{% static 'img/category/c1.jpg' %}" alt="" />
                            <a href="img/category/c1.jpg' %}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Sneaker for Sports</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{% static 'img/category/c2.jpg' %}" alt="" />
                            <a href="img/category/c2.jpg' %}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Sneaker for Sports</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{% static 'img/category/c3.jpg' %}" alt="" />
                            <a href="img/category/c3.jpg' %}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Product for Couple</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{% static 'img/category/c4.jpg' %}" alt="" />
                            <a href="img/category/c4.jpg' %}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Sneaker for Sports</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single-deal">
                    <div class="overlay"></div>
                    <img class="img-fluid w-100" src="{% static 'img/category/c5.jpg' %}" alt="" />
                    <a href="img/category/c5.jpg' %}" class="img-pop-up" target="_blank">
                        <div class="deal-details">
                            <h6 class="deal-title">Sneaker for Sports</h6>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End category Area -->
		<!-- start product Area -->
		<section class="owl-carousel active-product-area section_gap">
			<!-- single product slide -->
			<div class="single-product-slider">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-lg-6 text-center">
							<div class="section-title">
								<h1>Latest Products</h1>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
									eiusmod tempor incididunt ut labore et
									dolore
									magna aliqua.</p>
							</div>
						</div>
					</div>
					<div class="row">
                        {% for product in product_list %}
						<!-- single product -->
						<div class="col-lg-3 col-md-6">
							<div class="single-product">
                                {% if product.thumbnail_image %}
                                <img class="img-fluid" src="{{product.thumbnail_image.url}}" alt="">

                                {% else %}
								<img class="img-fluid" src="{% static 'img/product/p1.jpg' %}" alt="">


                                {% endif %}
								<div class="product-details">
									<h6>{{product.product_name}}</h6>
									<div class="price">
										<h6>${{product.price}}</h6>
										<!-- <h6 class="l-through">${{product.price}}</h6> -->
									</div>
									<div class="prd-bottom">
                                        {% if request.user.is_authenticated %}
										<a class="social-info add-to-cart" data-id="{{product.id}}">
											<span class="ti-bag"></span>
											<p class="hover-text">add to bag</p>
										</a>
                                        {% else %}
										<a href="{% url 'login' %}"class="social-info">
											<span class="ti-bag"></span>
											<p class="hover-text">add to bag</p>
										</a>
                                        {% endif %}

										<a href="{% url 'product_management:product_detail' product.pk %}" class="social-info">
											<span class="lnr lnr-move"></span>
											<p class="hover-text">view more</p>
										</a>
									</div>
								</div>
							</div>
						</div>
                        {% endfor %}
						
					</div>
				</div>
			</div>
			<!-- single product slide -->
			<div class="single-product-slider">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-lg-6 text-center">
							<div class="section-title">
								<h1>Coming Products</h1>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
									eiusmod tempor incididunt ut labore et
									dolore
									magna aliqua.</p>
							</div>
						</div>
					</div>
					<div class="row">
						{% for product in uppcoming_product_list %}
						<!-- single product -->
						<div class="col-lg-3 col-md-6">
							<div class="single-product">
                                {% if product.thumbnail_image %}
                                <img class="img-fluid" src="{{product.thumbnail_image.url}}" alt="">
                                {% else %}
								<img class="img-fluid" src="{% static 'img/product/p1.jpg' %}" alt="">
                                {% endif %}
								<div class="product-details">
									<h6>{{product.product_name}}</h6>
									<div class="price">
										<h6>${{product.price}}</h6>
										<!-- <h6 class="l-through">${{product.price}}</h6> -->
									</div>
									<div class="prd-bottom">

										<a href="{% url 'product_management:product_detail' product.pk %}" class="social-info">
											<span class="lnr lnr-move"></span>
											<p class="hover-text">view more</p>
										</a>
									</div>
								</div>
							</div>
						</div>
						{% empty %}
						<p>No Record Found</p>
                        {% endfor %}
						
					</div>
				</div>
			</div>
		</section>
		<!-- end product Area -->

<!-- Start brand Area -->
<section class="brand-area section_gap">
    <div class="container">
        <div class="row">
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'img/brand/1.png' %}" alt="" />
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'img/brand/2.png' %}" alt="" />
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'img/brand/3.png' %}" alt="" />
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'img/brand/4.png' %}" alt="" />
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'img/brand/5.png' %}" alt="" />
            </a>
        </div>
    </div>
</section>
<!-- End brand Area -->
 {% endblock %}

administration/templates/administration/my_profile.html
{% extends "base/base.html" %}
{% load static %}
{% block title %} {{object.first_name}} {{object.last_name}} {% endblock %}
{% block containt %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
	<div class="container">
		<div class="breadcrumb-banner d-flex flex-wrap align-items-center
			justify-content-end">
			<div class="col-first">
				<h1>{{object.first_name}} {{object.last_name}}</h1>
				<nav class="d-flex align-items-center">
					<a href="/">Home<span class="lnr lnr-arrow-right"></span></a>
					<a href="{% url 'administration:edit_user' object.id %}">Edit</a>
				</nav>
			</div>
		</div>
	</div>
</section>
<!-- End Banner Area -->

<!--================Single Product Area =================-->
<div class="product_image_area">
	<div class="container">
		<div class="row s_product_inner">

			<div class="col-lg-6">
				<div class="s_product_text">
					<ul class="list">
						<li><strong>Name : </strong> {{object.first_name}} {{object.last_name}}</li>
						<li><strong>Phone number : </strong> {{object.phone_no}}</li>
						<li><strong>Alternet Phone number : </strong>
							{{object.phone_no_2|default_if_none:'not Available'}}</li>
					</ul>
				</div>
				<div class="s_product_text">
					{% for i in object.address.all %}
					<div class="row">

						<div class="col-6">
							<h2>Address {{forloop.counter}} </h2>
						</div>
						<div class="col-6">
							<a href="{% url 'administration:edit_address' i.pk %}">Edit</a>
						</div>
					</div>
					<ul class="list">
						<li><strong>address : </strong> {{i.address_1}} {{i.address_2}}</li>
						<li><strong>city : </strong> {{i.city}}</li>
						<li><strong>state : </strong> {{i.state}}</li>
						<li><strong>zipcode : </strong> {{i.zipcode}}</li>
						<li><strong>country : </strong> {{i.country.name}}</li>
						<li><strong>Billing Address : </strong> {{i.billing}}</li>
						<li><strong>Shipping Address : </strong> {{i.shipping}}</li>

					</ul>
					{% endfor %}
				</div>
			</div>
		</div>

		<div class="col-lg-5 offset-lg-1">

			<div class="card_area d-flex align-items-center">
				<a class="primary-btn" href="{% url 'administration:add_address' object.id %}">
					Add to Address</a>
			</div>


		</div>
	</div>
</div>
<br>
<br>

{% endblock %}