order/urls.py
# from administration.models import Branch
from django.urls import path
from order import api
from order import views

app_name = 'order'
urlpatterns = [
    path('api/add-to-cart/<str:product_id>/',           api.AddToCart.as_view()),       #   add product to 
    path('your-cart/',              views.cart_list,    name='cart_list'),
    path('confirmation/<str:pk>',   views.confirmation,    name='confirmation'),

    
]

product_management/urls.py
# from administration.models import Branch
from django.urls import path
from product_management import views
app_name = 'product_management'

urlpatterns = [
    path('product-detail/<str:pk>', views.product_detail, name='product_detail'),
    path('all-products/',           views.ProductList.as_view(), name='product_list'),
    path('search/',                 views.filter_product, name='filter_product'),


]

swan_ecommerce/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',   include('django.contrib.auth.urls')),
    path('',            include('administration.urls', namespace='administration')),
    path('',            include('product_management.urls', namespace='product_management')),
    path('',            include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from swan_ecommerce.models import BaseModel
from administration.models import *
from product_management.models import *

from .choices import *
import string    
import random 
S = 5  # number of characters in the string.  

class Cart(BaseModel):
    cart_id     = models.CharField(('Order ID'),max_length=100, null=True)
    sub_total   = models.DecimalField(('Total'),max_digits=10, decimal_places=2, null=True)
    tax         = models.DecimalField(('Discount'),max_digits=10, decimal_places=2, default=18.00,null=True)
    total_price = models.DecimalField(('Total Payable'),max_digits=10, decimal_places=2, null=True)
    payment_status = models.IntegerField("Status", choices=PaymentStatus.choices, default=PaymentStatus.PENDING)

    def __str__(self):
        return (self.cart_id)

    def get_tax(self):
        tax_amt = (self.total_price * self.tax)/100
        return tax_amt

    def total_payable(self):
        tax_amt = (self.total_price * self.tax)/100
        total_payable = self.total_price + tax_amt
        return total_payable
        
    def save(self, *args, **kwargs):
        if not self.cart_id:
            cart_id = ''.join(random.choices(string.ascii_uppercase + string.digits, k = S))    
            self.cart_id = cart_id
        super(Cart, self).save(*args, **kwargs)

class CartItem(BaseModel):
    cart_id         = models.ForeignKey(Cart,   on_delete= models.CASCADE,  null=True)
    product         = models.ForeignKey(Product, on_delete= models.SET_NULL, null=True)
    product_name    = models.CharField(max_length=100, null=True)
    product_category= models.CharField(max_length=100, null=True)
    price           = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    quantity        = models.DecimalField("Purchased Quantity",max_digits=10, decimal_places=2, null=True)
    total_price     = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    # def save(self, *args, **kwargs):
    #     if not self.total_price == 1:
    #         self.total_price = float(self.price) * float(self.quantity)
    #     super(CartItem, self).save(*args, **kwargs)

order/views.py
import re
from django.shortcuts import render
from order.models import *
from .utils import mail_order_detail

def cart_list(request):
    if 'current_cart' in request.session.keys():
        current_cart = request.session['current_cart']
        cart_obj = Cart.objects.get(cart_id = current_cart)
    else:
        cart_obj = Cart.objects.create()
        request.session['current_cart'] = cart_obj.cart_id
        current_cart = request.session['current_cart']
    cart_items = CartItem.objects.filter(cart_id = cart_obj)
    total_payable = 0
    for i in cart_items:
        total_payable = total_payable + i.total_price
        total_payable = total_payable
    context = { 
        'cart_items':cart_items,
        'total_payable':total_payable,
        'cart_obj':cart_obj
    }
    return render(request,'order/cart_list.html',context)

def confirmation(request,pk):
    cart_obj = Cart.objects.get(pk=pk)
    cart_items = CartItem.objects.filter(cart_id = cart_obj)
    user = RootUser.objects.get(username = request.user.username)
    try:
        billing_address = user.address.get(is_billing=True)
        shipping_address = user.address.get(is_shipping=True)

    except:
        billing_address = user.address.last()
        shipping_address = user.address.last()

    total_payable = 0
    for i in cart_items:
        total_payable = total_payable + i.total_price
        total_payable = total_payable
    cart_obj.total_price=total_payable 
    cart_obj.save()
    mail_order_detail(user.email,cart_obj.id,user,billing_address.id,shipping_address.id,total_payable)
    # task_mail_order_detail.delay
    context = { 
        'cart_items':cart_items,
        'cart_obj':cart_obj,
        'user':user,
        'billing_address':billing_address,
        'shipping_address':shipping_address,
        'total':total_payable,
    }
    return render(request,'order/confirmation.html',context)

order/templates/order/cart_list.html
{% extends "base/base.html" %}
{% load static %}
{% block title %} Cart {% endblock %}
{% block containt %} <section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center
            justify-content-end">
            <div class="col-first">
                <h1>Shopping Cart</h1>
                <nav class="d-flex align-items-center">
                    <a href="/">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="{{request.path}}">Cart</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Cart Area =================-->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in cart_items %}
                        <tr>
                            <td>
                                <div class="media">
                                    <div class="media-body">
                                        <p>{{i.product_name}}</p>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <h5>{{i.price}}</h5>
                            </td>
                            <td>
                                <h5>{{i.quantity}}</h5>
                            </td>
                            <td>
                                <h5>{{i.total_price}}</h5>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td>Your Cart is Empty</td>
                        </tr> {% endfor %}


                        <tr>
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <h5>Total Payable</h5>
                            </td>
                            <td>
                                <h5>{{total_payable}}</h5>
                            </td>
                        </tr>

                        <tr class="out_button_area">
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <div class="checkout_btn_inner d-flex
                                    align-items-center">
                                    <a class="gray_btn" href="{% url
                                        'product_management:product_list' %}">Continue
                                        Shopping</a>
                                    {% if cart_items %}
                                    <a class="primary-btn" href="{% url
                                        'order:confirmation' cart_obj.id %}">Proceed
                                        to checkout</a>
                                    {% endif %}

                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}
<!--================End Cart Area =================-->

order/templates/order/confirmation.html
{% extends "base/base.html" %}
{% load static %}
{% block title %} Cart {% endblock %}
{% block containt %} 
	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Confirmation</h1>
					<nav class="d-flex align-items-center">
						<a href="/">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="{{request.path}}">Confirmation</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

	<!--================Order Details Area =================-->
	<section class="order_details section_gap">
		<div class="container">
			<h3 class="title_confirmation">Thank you. Your order has been received.</h3>
			<div class="row order_d_inner">
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Order Info</h4>
						<ul class="list">
							<li><a ><span>Order number</span> : {{cart_obj.cart_id}}</a></li>
							<li><a ><span>Date</span> : {{cart_obj.created|date:"d/m/Y"}}</a></li>
							<li><a ><span>Total</span> : USD{{cart_obj.total_price}}</a></li>
							<li><a ><span>Payment method</span> : Check payments</a></li>
						</ul>
					</div>
				</div>
				
				{% if address_status %}
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Billing Address</h4>
						<ul class="list">
							<li><a ><span>Street</span> : {{address.address_1}} {{address.address_2}}</a></li>
							<li><a ><span>City</span> : {{address.city}}</a></li>
							<li><a ><span>Country</span> :  {{address.country.name}}</a></li>
							<li><a ><span>Postcode </span> :  {{address.zipcode}}</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Shipping Address</h4>
						<ul class="list">
							<li><a ><span>Street</span> : {{address.address_1}} {{address.address_2}}</a></li>
							<li><a ><span>City</span> : {{address.city}}</a></li>
							<li><a ><span>Country</span> :  {{address.country.name}}</a></li>
							<li><a ><span>Postcode </span> :  {{address.zipcode}}</a></li>
						</ul>
					</div>
				</div>
				{% endif %}

			</div>
			<div class="order_details_table">
				<h2>Order Details</h2>
				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th scope="col">Product</th>
								<th scope="col">Quantity</th>
								<th scope="col">Total</th>
							</tr>
						</thead>
						<tbody>
                            {% for i in cart_items %}
                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="media-body">
                                            <p>{{i.product_name}}</p>
                                        </div>
                                    </div>
                                </td>

                                <td>
                                    <h5>{{i.quantity}}</h5>
                                </td>
                                <td>
                                    <h5>{{i.total_price}}</h5>
                                </td>
                            </tr>
                            {% endfor %}
                            <tr>
								<td>
									<h4>total</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>${{total}}</p>
								</td>
							</tr>
							<tr>
								<td>
									<h4>Tax</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>${{cart_obj.get_tax}}</p>
								</td>
							</tr>
							<tr>
								<td>
									<h4>Total Payable</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>${{cart_obj.total_payable}}</p>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</section>
	<!--================End Order Details Area =================-->

{% endblock %}
    <!--================End Cart Area =================-->

order/templates/order/mail_order_detail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Reciept</title>
</head>
<body>
	<section class="order_details">
		<div class="container">
			<h3 class="title_confirmation">Thank you. Your order has been received.</h3>
			<div class="row order_d_inner">
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Customer Info</h4>
						<ul class="list">
							<li><a ><span>Name</span> : {{user.first_name}} {{user.last_name}}</a></li>
							<li><a ><span>Phone number</span> : {{user.phone_no}}</a></li>
							<li><a ><span>Alrenet Phone number</span> : {{user.phone_no_2|default_if_none:'not Available'}}</a></li>

						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="order_details section_gap">
		<div class="container">
			<div class="row order_d_inner">
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Order Info</h4>
						<ul class="list">
							<li><a ><span>Order number</span> : {{cart_obj.cart_id}}</a></li>
							<li><a ><span>Date</span> : {{cart_obj.created|date:"d/m/Y"}}</a></li>
							<li><a ><span>Total</span> : USD{{cart_obj.total_price}}</a></li>
							<li><a ><span>Payment method</span> : Check payments</a></li>
						</ul>
					</div>
				</div>
				
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Billing Address</h4>
						<ul class="list">
							<li><a ><span>Street</span> : {{billing_address.address_1}} {{address.address_2}}</a></li>
							<li><a ><span>City</span> : {{billing_address.city}}</a></li>
							<li><a ><span>Country</span> :  {{billing_address.country.name}}</a></li>
							<li><a ><span>Postcode </span> :  {{billing_address.zipcode}}</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Shipping Address</h4>
						<ul class="list">
							<li><a ><span>Street</span> : {{shipping_address.address_1}} {{shipping_address.address_2}}</a></li>
							<li><a ><span>City</span> : {{shipping_address.city}}</a></li>
							<li><a ><span>Country</span> :  {{shipping_address.country.name}}</a></li>
							<li><a ><span>Postcode </span> :  {{shipping_address.zipcode}}</a></li>
						</ul>
					</div>
				</div>

			</div>
			<div class="order_details_table">
				<h2>Order Details</h2>
				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th scope="col">Product</th>
								<th scope="col">Quantity</th>
								<th scope="col">Total</th>
							</tr>
						</thead>
						<tbody>
                            {% for i in cart_items %}
                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="media-body">
                                            <p>{{i.product_name}}</p>
                                        </div>
                                    </div>
                                </td>

                                <td>
                                    <h5>{{i.quantity}}</h5>
                                </td>
                                <td>
                                    <h5>{{i.total_price}}</h5>
                                </td>
                            </tr>
                            {% endfor %}
                            <tr>
								<td>
									<h4>total</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>${{total}}</p>
								</td>
							</tr>
							<tr>
								<td>
									<h4>Tax</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>${{cart_obj.get_tax}}</p>
								</td>
							</tr>
							<tr>
								<td>
									<h4>Total Payable</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>${{cart_obj.total_payable}}</p>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</section>
</body>
</html>